### ISSUE TITLE
F reading in as FALSE in plot

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/TEMPEST-1-porewater#7]
https://github.com/COMPASS-DOE/TEMPEST-1-porewater/blob/4e6beb2522bdf2c19020219b8936bf3aa3784d5a/scripts/teros_prep.Rmd#L90

**Comment by stephpenn1** [comment]
Note we are discussing this via https://github.com/COMPASS-DOE/data-workflows/issues/186

**Comment by amyerspigg** [comment]
Resolved in other place
